# Python Pandas for Beginners 

### Priyaranjan Mohanty

**What is Pandas ?**

Pandas is a software library written for the Python programming language for data manipulation and analysis. 
In particular, it offers data structures and operations for manipulating numerical tables and time series. 
It is free software released under the three-clause BSD license.

The name is derived from the term "panel data", an econometrics term for data sets that include observations over multiple time periods for the same individuals.

**Pandas support 2 types of Data Structures :- **

    a) Dataframe
    b) Series 

**Dataframe -**
pandas DataFrame (in a Jupyter Notebook) appears to be nothing more than an ordinary table of data consisting of rows and columns. Hiding beneath the surface are the three components--the index, columns, and data (also known as values)

So as to understand the Dataframe better , lets load Movies data into a Dataframe and explore the methods and attributes avilable with Dataframe .

In [78]:
import pandas as pd

### Import the Pandas package with pd as alias

#### Use the read_csv function to read in the movie dataset

 read_csv is an important pandas function to read csv files and do operations on it.

In [79]:
# Find the folder path of your current working directory

import os

os.getcwd()

'C:\\Users\\itzpr'

In [80]:
# read a CSV file into PythoOn and return a DataFrame as output
Movie_DF = pd.read_csv('movie.csv')

In [81]:
Movie_DF

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
4887,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
4888,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
4889,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
4890,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
4891,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
4892,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
4893,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
4894,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
4895,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
4896,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
4897,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
4898,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
4899,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
4900,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
4901,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
4902,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
4903,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
4904,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
4905,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
4906,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
4907,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
4908,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
4909,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
4910,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [83]:
pd.read_csv(r'C:\Users\itzpr\movie.csv')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
4887,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
4888,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
4889,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
4890,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
4891,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
4892,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
4893,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
4894,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
4895,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
4896,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
4897,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
4898,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
4899,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
4900,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
4901,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
4902,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
4903,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
4904,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
4905,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
4906,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
4907,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
4908,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
4909,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
4910,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [84]:
pd.read_csv(r'C:/Users/itzpr/movie.csv')

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4886,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
4887,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
4888,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
4889,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
4890,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
4891,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
4892,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
4893,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
4894,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
4895,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
4896,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
4897,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
4898,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
4899,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
4900,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
4901,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
4902,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
4903,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
4904,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
4905,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
4906,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
4907,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
4908,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
4909,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
4910,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

#### Let's check the dataype returned by read_csv() and confirm that indeed the output is of type Dataframe

In [85]:
# Check the Data type of the output returned by pd.read_csv()

print(type(Movie_DF))

<class 'pandas.core.frame.DataFrame'>

#### Now , that we have read the CSV file into a Pandas Dataframe - 
       a) We check the data for first 5 observations using head() 
       b) we can also check the data for last 5 observations using tail()

In [86]:
# Show the content of first 5 observations in a Dataframe

Movie_DF.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [87]:
# Show the content of last 5 observations in a Dataframe

Movie_DF.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

You will observe the following in the above Dataframe content displayed -
    
    a) Observation : Each Row of Data is called an Observation 
    b) INDEX : Provides a label to the Rows of a Dataframe 
    c) Columns : Each column also called Attribute / Feature contains a homogenous set of data 
    d) Column Name : Each column is being uniquely identified through a Column Name


Pandas uses NaN (not a number) to represent missing values.

### Do you Know -

You can control how many observations to be displayed as part of head() or tail()

In [88]:
# Show the content of first 3 observations in a Dataframe

Movie_DF.head(3)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000

### Accessing the 3 individual components of a DataFrame

    the index, 
    columns, 
    and data
    

Each of these components is itself a Python object with its own unique attributes and methods.

In [89]:
# Fetch all the Index values from the Dataframe.

Movie_index = Movie_DF.index

print("The values in the index column is : " , Movie_index)

print('\n')

print("The Data Type of the Index is     : " , type(Movie_index))

The values in the index column is :  RangeIndex(start=0, stop=4916, step=1)


The Data Type of the Index is     :  <class 'pandas.core.indexes.range.RangeIndex'>

In [90]:
# Fetch all the Column Names from the Dataframe.

Movie_Col_Names = Movie_DF.columns

print("The Column Names are  : " , Movie_Col_Names)

print('\n')

print("The Data Type of the Column Names is     : " , type(Movie_Col_Names))

The Column Names are  :  Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')


The Data Type of the Column Names is     :  <class 'pandas.core.indexes.base.Index'>

In [91]:
# Fetch all the Values from the Dataframe.

Movie_Values = Movie_DF.values

print("The Values in the Dataframe are  : " , Movie_Values)

print('\n')

print("The Data Type of the Values is     : " , type(Movie_Values))

The Values in the Dataframe are  :  [['Color' 'James Cameron' 723.0 ... 7.9 1.78 33000]
 ['Color' 'Gore Verbinski' 302.0 ... 7.1 2.35 0]
 ['Color' 'Sam Mendes' 602.0 ... 6.8 2.35 85000]
 ...
 ['Color' 'Benjamin Roberds' 13.0 ... 6.3 nan 16]
 ['Color' 'Daniel Hsia' 14.0 ... 6.3 2.35 660]
 ['Color' 'Jon Gunn' 43.0 ... 6.6 1.85 456]]


The Data Type of the Values is     :  <class 'numpy.ndarray'>

**How to check the Structure of a DataFrame **

Structure of a Dataframe can be enquired / checked using info() method of a Dataframe object

In [18]:
# Display the structure of a Dataframe

Movie_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
color                        4897 non-null object
director_name                4814 non-null object
num_critic_for_reviews       4867 non-null float64
duration                     4901 non-null float64
director_facebook_likes      4814 non-null float64
actor_3_facebook_likes       4893 non-null float64
actor_2_name                 4903 non-null object
actor_1_facebook_likes       4909 non-null float64
gross                        4054 non-null float64
genres                       4916 non-null object
actor_1_name                 4909 non-null object
movie_title                  4916 non-null object
num_voted_users              4916 non-null int64
cast_total_facebook_likes    4916 non-null int64
actor_3_name                 4893 non-null object
facenumber_in_poster         4903 non-null float64
plot_keywords                4764 non-null object
movie_imdb_link              4916 non-null object
num_user_for_reviews         4895 non-null float64
language                     4904 non-null object
country                      4911 non-null object
content_rating               4616 non-null object
budget                       4432 non-null float64
title_year                   4810 non-null float64
actor_2_facebook_likes       4903 non-null float64
imdb_score                   4916 non-null float64
aspect_ratio                 4590 non-null float64
movie_facebook_likes         4916 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [19]:
# Just display the Data types of the columns of a Dataframe

Movie_DF.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

**We can extract the Count of each DataTypes in a Datframe using get_dtype_counts()**

In [92]:
# Display the cummulative Data Type Counts in a Dataframe

Movie_DF.get_dtype_counts()

float64    13
int64       3
object     12
dtype: int64

**Series**

Time to explore the Series object in Pandas .

A Series is a single column of data from a DataFrame. 
It is a single dimension of data, composed of just an index and the data.

In [93]:
# Extract the values in the column 'director_name' from the Movies DataFrame

Movie_DF['director_name']

0            James Cameron
1           Gore Verbinski
2               Sam Mendes
3        Christopher Nolan
4              Doug Walker
5           Andrew Stanton
6                Sam Raimi
7             Nathan Greno
8              Joss Whedon
9              David Yates
10             Zack Snyder
11            Bryan Singer
12            Marc Forster
13          Gore Verbinski
14          Gore Verbinski
15             Zack Snyder
16          Andrew Adamson
17             Joss Whedon
18            Rob Marshall
19        Barry Sonnenfeld
20           Peter Jackson
21               Marc Webb
22            Ridley Scott
23           Peter Jackson
24             Chris Weitz
25           Peter Jackson
26           James Cameron
27           Anthony Russo
28              Peter Berg
29         Colin Trevorrow
               ...
4886            Eric Eason
4887              Uwe Boll
4888     Richard Linklater
4889       Joseph Mazzella
4890          Travis Legge
4891         Alex Kendrick
4892         Marcus Nispel
4893       Brandon Landers
4894           Jay Duplass
4895            Jim Chuchu
4896            Daryl Wein
4897           Jason Trost
4898           John Waters
4899       Olivier Assayas
4900          Jafar Panahi
4901         Ivan Kavanagh
4902      Kiyoshi Kurosawa
4903          Tadeo Garcia
4904    Thomas L. Phillips
4905       Ash Baron-Cohen
4906         Shane Carruth
4907      Neill Dela Llana
4908      Robert Rodriguez
4909       Anthony Vallone
4910          Edward Burns
4911           Scott Smith
4912                   NaN
4913      Benjamin Roberds
4914           Daniel Hsia
4915              Jon Gunn
Name: director_name, Length: 4916, dtype: object

In [94]:
# Extract the values in the column 'director_name' from the Movies DataFrame usinf dot approach
# Note - This approach is not encouraged as it will not work when a column name has blank space

Movie_DF.director_name

0            James Cameron
1           Gore Verbinski
2               Sam Mendes
3        Christopher Nolan
4              Doug Walker
5           Andrew Stanton
6                Sam Raimi
7             Nathan Greno
8              Joss Whedon
9              David Yates
10             Zack Snyder
11            Bryan Singer
12            Marc Forster
13          Gore Verbinski
14          Gore Verbinski
15             Zack Snyder
16          Andrew Adamson
17             Joss Whedon
18            Rob Marshall
19        Barry Sonnenfeld
20           Peter Jackson
21               Marc Webb
22            Ridley Scott
23           Peter Jackson
24             Chris Weitz
25           Peter Jackson
26           James Cameron
27           Anthony Russo
28              Peter Berg
29         Colin Trevorrow
               ...
4886            Eric Eason
4887              Uwe Boll
4888     Richard Linklater
4889       Joseph Mazzella
4890          Travis Legge
4891         Alex Kendrick
4892         Marcus Nispel
4893       Brandon Landers
4894           Jay Duplass
4895            Jim Chuchu
4896            Daryl Wein
4897           Jason Trost
4898           John Waters
4899       Olivier Assayas
4900          Jafar Panahi
4901         Ivan Kavanagh
4902      Kiyoshi Kurosawa
4903          Tadeo Garcia
4904    Thomas L. Phillips
4905       Ash Baron-Cohen
4906         Shane Carruth
4907      Neill Dela Llana
4908      Robert Rodriguez
4909       Anthony Vallone
4910          Edward Burns
4911           Scott Smith
4912                   NaN
4913      Benjamin Roberds
4914           Daniel Hsia
4915              Jon Gunn
Name: director_name, Length: 4916, dtype: object

**Now , lets check the Data Type of the values extracted from a single column of a Dataframe **

In [95]:
# Display the Data type of a Column extracted from a DataFrame

print(type(Movie_DF['director_name']))

<class 'pandas.core.series.Series'>

**Explore the Methods available with SERIES **

let's select two Series with different data types from the Movie Dataframe. 
The director_name column contains strings, formally an object data type, and the column actor_1_facebook_likes contains numerical data, formally float64:

In [96]:
# Create 2 Series from the Movies Dataframe.

director = Movie_DF['director_name']
actor_1_fb_likes = Movie_DF['actor_1_facebook_likes']

print(type(director))
print(type(actor_1_fb_likes))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

**head() with SERIES object **

head() method is available with SERIES Dataframe , using which we can fetch specific number of elements from the top ( default is 5 elements )

In [25]:
print(director.head())

print('\n')  # Print an Empty Line 

print(actor_1_fb_likes.head(3))

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object


0     1000.0
1    40000.0
2    11000.0
Name: actor_1_facebook_likes, dtype: float64

**value_counts() method for SERIES with String / Object data type**

This method returns the count of Unique Values in a Series .

In [26]:
# Display the Count of Unique values in a SERIES 

print(director.value_counts())

Steven Spielberg            26
Woody Allen                 22
Martin Scorsese             20
Clint Eastwood              20
Ridley Scott                16
Spike Lee                   16
Steven Soderbergh           15
Renny Harlin                15
Oliver Stone                14
Tim Burton                  14
Robert Rodriguez            13
Ron Howard                  13
Robert Zemeckis             13
Joel Schumacher             13
Barry Levinson              13
Tony Scott                  12
Kevin Smith                 12
Brian De Palma              12
Michael Bay                 12
Chris Columbus              11
Richard Linklater           11
Francis Ford Coppola        11
Rob Reiner                  11
Sam Raimi                   11
Richard Donner              11
Shawn Levy                  11
David Fincher               10
Wes Craven                  10
John McTiernan              10
Bobby Farrelly              10
                            ..
Paul Bartel                  1
Christopher Scott Cherot     1
Tom Walsh                    1
Trent Cooper                 1
Beeban Kidron                1
Marcos Siega                 1
Piyush Dinker Pandya         1
Nicholaus Goossen            1
Dan Curtis                   1
Babak Najafi                 1
Peter Cousens                1
Joe Camp                     1
Zoran Lisinac                1
Keith Gordon                 1
Takao Okawara                1
Gabriela Tagliavini          1
Wil Shriner                  1
Mikel Rueda                  1
Tom Reeve                    1
Malcolm Goodwin              1
Anthony Hemingway            1
Steve Gomer                  1
Nick Hurran                  1
Mike Bigelow                 1
Mark Sandrich                1
Jon Wright                   1
Hark Tsui                    1
Sacha Bennett                1
Mark Rydell                  1
Mervyn LeRoy                 1
Name: director_name, Length: 2397, dtype: int64

**using describe() method to extract Statistical summary of a Series of Numerical datatype**

In [27]:
# Display the Statistical Summary of a Series of Numerical Data Type

print(actor_1_fb_likes.describe())

count      4909.000000
mean       6494.488491
std       15106.986884
min           0.000000
25%         607.000000
50%         982.000000
75%       11000.000000
max      640000.000000
Name: actor_1_facebook_likes, dtype: float64

**describe() method shows different outputs in case of Categorical datatype **

In [28]:
# Display the Summary of a Series of Categorical Data Type

print(director.describe())

count                 4814
unique                2397
top       Steven Spielberg
freq                    26
Name: director_name, dtype: object

**Checking whether any value in SERIES is a Missing Value or NaN**

We can identify if a specific value in a Series is missing by using isnull() method

In [29]:
# Check if any value in a Series is Missing 

director.isnull()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
4886    False
4887    False
4888    False
4889    False
4890    False
4891    False
4892    False
4893    False
4894    False
4895    False
4896    False
4897    False
4898    False
4899    False
4900    False
4901    False
4902    False
4903    False
4904    False
4905    False
4906    False
4907    False
4908    False
4909    False
4910    False
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [97]:
director.isnull().sum()

102

Once , we have identified whether there are Missing Values in a Series or Not , we can address the Missing Values in 2 ways -

    a) Replace the Missing Values with some Constant or by output of an Expression 
    b) Drop those elements with Missing values from the Series

In [98]:
# Replace the Missing Values with 0 

director_flled = director.fillna(0)

print("Count of Non Missing Values before applying fillna() :" ,director.count())
print("Count of Non Missing Values after applying fillna()  :" ,director_flled.count())

Count of Non Missing Values before applying fillna() : 4814
Count of Non Missing Values after applying fillna()  : 4916

In [99]:
# Replace the Missing Values with 0 

director_NA_Dropped = director.dropna()

print("Count of elements before applying dropna() :" ,director.size)
print("Count of elements after applying dropna()  :" ,director_NA_Dropped.size)

Count of elements before applying dropna() : 4916
Count of elements after applying dropna()  : 4814

**Applying 'Operations' on a SERIES **

Operations applied on a SERIES is Vectorized - meaning an operation applied on a Series , gets applied on each element of the Series.

In [100]:
# Applying multiplaction operator on Series containing String data type 
# Resulting in each Value being concatenated to itself

director * 3

0                 James CameronJames CameronJames Cameron
1              Gore VerbinskiGore VerbinskiGore Verbinski
2                          Sam MendesSam MendesSam Mendes
3       Christopher NolanChristopher NolanChristopher ...
4                       Doug WalkerDoug WalkerDoug Walker
5              Andrew StantonAndrew StantonAndrew Stanton
6                             Sam RaimiSam RaimiSam Raimi
7                    Nathan GrenoNathan GrenoNathan Greno
8                       Joss WhedonJoss WhedonJoss Whedon
9                       David YatesDavid YatesDavid Yates
10                      Zack SnyderZack SnyderZack Snyder
11                   Bryan SingerBryan SingerBryan Singer
12                   Marc ForsterMarc ForsterMarc Forster
13             Gore VerbinskiGore VerbinskiGore Verbinski
14             Gore VerbinskiGore VerbinskiGore Verbinski
15                      Zack SnyderZack SnyderZack Snyder
16             Andrew AdamsonAndrew AdamsonAndrew Adamson
17                      Joss WhedonJoss WhedonJoss Whedon
18                   Rob MarshallRob MarshallRob Marshall
19       Barry SonnenfeldBarry SonnenfeldBarry Sonnenfeld
20                Peter JacksonPeter JacksonPeter Jackson
21                            Marc WebbMarc WebbMarc Webb
22                   Ridley ScottRidley ScottRidley Scott
23                Peter JacksonPeter JacksonPeter Jackson
24                      Chris WeitzChris WeitzChris Weitz
25                Peter JacksonPeter JacksonPeter Jackson
26                James CameronJames CameronJames Cameron
27                Anthony RussoAnthony RussoAnthony Russo
28                         Peter BergPeter BergPeter Berg
29          Colin TrevorrowColin TrevorrowColin Trevorrow
                              ...
4886                       Eric EasonEric EasonEric Eason
4887                             Uwe BollUwe BollUwe Boll
4888    Richard LinklaterRichard LinklaterRichard Link...
4889        Joseph MazzellaJoseph MazzellaJoseph Mazzella
4890                 Travis LeggeTravis LeggeTravis Legge
4891              Alex KendrickAlex KendrickAlex Kendrick
4892              Marcus NispelMarcus NispelMarcus Nispel
4893        Brandon LandersBrandon LandersBrandon Landers
4894                    Jay DuplassJay DuplassJay Duplass
4895                       Jim ChuchuJim ChuchuJim Chuchu
4896                       Daryl WeinDaryl WeinDaryl Wein
4897                    Jason TrostJason TrostJason Trost
4898                    John WatersJohn WatersJohn Waters
4899        Olivier AssayasOlivier AssayasOlivier Assayas
4900                 Jafar PanahiJafar PanahiJafar Panahi
4901              Ivan KavanaghIvan KavanaghIvan Kavanagh
4902     Kiyoshi KurosawaKiyoshi KurosawaKiyoshi Kurosawa
4903                 Tadeo GarciaTadeo GarciaTadeo Garcia
4904    Thomas L. PhillipsThomas L. PhillipsThomas L. ...
4905        Ash Baron-CohenAsh Baron-CohenAsh Baron-Cohen
4906              Shane CarruthShane CarruthShane Carruth
4907     Neill Dela LlanaNeill Dela LlanaNeill Dela Llana
4908     Robert RodriguezRobert RodriguezRobert Rodriguez
4909        Anthony ValloneAnthony ValloneAnthony Vallone
4910                 Edward BurnsEdward BurnsEdward Burns
4911                    Scott SmithScott SmithScott Smith
4912                                                  NaN
4913     Benjamin RoberdsBenjamin RoberdsBenjamin Roberds
4914                    Daniel HsiaDaniel HsiaDaniel Hsia
4915                             Jon GunnJon GunnJon Gunn
Name: director_name, Length: 4916, dtype: object

In [33]:
# Applying Division operator with the Series containing Numeric Data 
# Resulting in each value being divided by 100

actor_1_fb_likes / 100

0        10.00
1       400.00
2       110.00
3       270.00
4         1.31
5         6.40
6       240.00
7         7.99
8       260.00
9       250.00
10      150.00
11      180.00
12        4.51
13      400.00
14      400.00
15      150.00
16      220.00
17      260.00
18      400.00
19      100.00
20       50.00
21      150.00
22        8.91
23       50.00
24      160.00
25       60.00
26      290.00
27      210.00
28      140.00
29       30.00
         ...
4886      0.93
4887      9.86
4888      0.05
4889      3.13
4890      3.70
4891      0.51
4892      6.30
4893      7.20
4894      8.30
4895      1.47
4896      3.31
4897      4.07
4898      4.62
4899      5.76
4900      0.05
4901      0.10
4902      0.89
4903      0.21
4904      7.85
4905      7.89
4906      2.91
4907      0.00
4908      1.21
4909      0.45
4910      2.96
4911      6.37
4912      8.41
4913      0.00
4914      9.46
4915      0.86
Name: actor_1_facebook_likes, Length: 4916, dtype: float64

### **Chaining Series methods together**

In Python, every variable is an object, and all objects have attributes and methods that refer to or return more objects. The sequential invocation of methods using the dot notation is referred to as method chaining. Pandas is a library that lends itself well to method chaining, as many Series and DataFrame methods return more Series and DataFrames, upon which more methods can be called.

In [101]:
director.value_counts()

Steven Spielberg            26
Woody Allen                 22
Martin Scorsese             20
Clint Eastwood              20
Ridley Scott                16
Spike Lee                   16
Steven Soderbergh           15
Renny Harlin                15
Oliver Stone                14
Tim Burton                  14
Robert Rodriguez            13
Ron Howard                  13
Robert Zemeckis             13
Joel Schumacher             13
Barry Levinson              13
Tony Scott                  12
Kevin Smith                 12
Brian De Palma              12
Michael Bay                 12
Chris Columbus              11
Richard Linklater           11
Francis Ford Coppola        11
Rob Reiner                  11
Sam Raimi                   11
Richard Donner              11
Shawn Levy                  11
David Fincher               10
Wes Craven                  10
John McTiernan              10
Bobby Farrelly              10
                            ..
Paul Bartel                  1
Christopher Scott Cherot     1
Tom Walsh                    1
Trent Cooper                 1
Beeban Kidron                1
Marcos Siega                 1
Piyush Dinker Pandya         1
Nicholaus Goossen            1
Dan Curtis                   1
Babak Najafi                 1
Peter Cousens                1
Joe Camp                     1
Zoran Lisinac                1
Keith Gordon                 1
Takao Okawara                1
Gabriela Tagliavini          1
Wil Shriner                  1
Mikel Rueda                  1
Tom Reeve                    1
Malcolm Goodwin              1
Anthony Hemingway            1
Steve Gomer                  1
Nick Hurran                  1
Mike Bigelow                 1
Mark Sandrich                1
Jon Wright                   1
Hark Tsui                    1
Sacha Bennett                1
Mark Rydell                  1
Mervyn LeRoy                 1
Name: director_name, Length: 2397, dtype: int64

In [102]:
# Example of Method Chaining 

director.value_counts().head(3)

Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Name: director_name, dtype: int64

A common way to count the number of missing values is to chain the sum method after isnull

In [35]:
# Find the total number of Missing values in a SERIES 

actor_1_fb_likes.isnull().sum()

7

## Index of a DataFrame 

The index of a DataFrame provides a label for each of the rows. 
If no index is explicitly provided upon DataFrame creation, then by default, a RangeIndex is created with labels as integers from 0 to n-1, where n is the number of rows.

There are 2 ways , we can have an explicit Index Label -
          
      a) Defining one of the Column as Index during the read_csv() call 
      b) Setting the Index to a column after read_csv()

In [103]:
# Specify the Index Column during the read_csv() step 

Movie_DF2 = pd.read_csv('movie.csv', 
                        index_col='movie_title')

print(Movie_DF2.head())

                                            color      director_name  \
movie_title
Avatar                                      Color      James Cameron
Pirates of the Caribbean: At World's End    Color     Gore Verbinski
Spectre                                     Color         Sam Mendes
The Dark Knight Rises                       Color  Christopher Nolan
Star Wars: Episode VII - The Force Awakens    NaN        Doug Walker

                                            num_critic_for_reviews  duration  \
movie_title
Avatar                                                       723.0     178.0
Pirates of the Caribbean: At World's End                     302.0     169.0
Spectre                                                      602.0     148.0
The Dark Knight Rises                                        813.0     164.0
Star Wars: Episode VII - The Force Awakens                     NaN       NaN

                                            director_facebook_likes  \
movie_title
Avatar                                                          0.0
Pirates of the Caribbean: At World's End                      563.0
Spectre                                                         0.0
The Dark Knight Rises                                       22000.0
Star Wars: Episode VII - The Force Awakens                    131.0

                                            actor_3_facebook_likes  \
movie_title
Avatar                                                       855.0
Pirates of the Caribbean: At World's End                    1000.0
Spectre                                                      161.0
The Dark Knight Rises                                      23000.0
Star Wars: Episode VII - The Force Awakens                     NaN

                                                actor_2_name  \
movie_title
Avatar                                      Joel David Moore
Pirates of the Caribbean: At World's End       Orlando Bloom
Spectre                                         Rory Kinnear
The Dark Knight Rises                         Christian Bale
Star Wars: Episode VII - The Force Awakens        Rob Walker

                                            actor_1_facebook_likes  \
movie_title
Avatar                                                      1000.0
Pirates of the Caribbean: At World's End                   40000.0
Spectre                                                    11000.0
The Dark Knight Rises                                      27000.0
Star Wars: Episode VII - The Force Awakens                   131.0

                                                  gross  \
movie_title
Avatar                                      760505847.0
Pirates of the Caribbean: At World's End    309404152.0
Spectre                                     200074175.0
The Dark Knight Rises                       448130642.0
Star Wars: Episode VII - The Force Awakens          NaN

                                                                     genres  \
movie_title
Avatar                                      Action|Adventure|Fantasy|Sci-Fi
Pirates of the Caribbean: At World's End           Action|Adventure|Fantasy
Spectre                                           Action|Adventure|Thriller
The Dark Knight Rises                                       Action|Thriller
Star Wars: Episode VII - The Force Awakens                      Documentary

                                            ... num_user_for_reviews  \
movie_title                                 ...
Avatar                                      ...               3054.0
Pirates of the Caribbean: At World's End    ...               1238.0
Spectre                                     ...                994.0
The Dark Knight Rises                       ...               2701.0
Star Wars: Episode VII - The Force Awakens  ...                  NaN

                                            language  country content_rating  \
movie_title
Avatar                                       English      USA          PG-13
Pirates of the Caribbean: At World's End     English      USA          PG-13
Spectre                                      English       UK          PG-13
The Dark Knight Rises                        English      USA          PG-13
Star Wars: Episode VII - The Force Awakens       NaN      NaN            NaN

                                                 budget title_year  \
movie_title
Avatar                                      237000000.0     2009.0
Pirates of the Caribbean: At World's End    300000000.0     2007.0
Spectre                                     245000000.0     2015.0
The Dark Knight Rises                       250000000.0     2012.0
Star Wars: Episode VII - The Force Awakens          NaN        NaN

                                           actor_2_facebook_likes  imdb_score  \
movie_title
Avatar                                                      936.0         7.9
Pirates of the Caribbean: At World's End                   5000.0         7.1
Spectre                                                     393.0         6.8
The Dark Knight Rises                                     23000.0         8.5
Star Wars: Episode VII - The Force Awakens                   12.0         7.1

                                           aspect_ratio movie_facebook_likes
movie_title
Avatar                                             1.78                33000
Pirates of the Caribbean: At World's End           2.35                    0
Spectre                                            2.35                85000
The Dark Knight Rises                              2.35               164000
Star Wars: Episode VII - The Force Awakens          NaN                    0

[5 rows x 27 columns]

In [104]:
Movie_DF.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [105]:
# Change the Index Column after the read_csv() step 

Movie_DF3 = Movie_DF.set_index('movie_title')

print(Movie_DF3.head())

                                            color      director_name  \
movie_title
Avatar                                      Color      James Cameron
Pirates of the Caribbean: At World's End    Color     Gore Verbinski
Spectre                                     Color         Sam Mendes
The Dark Knight Rises                       Color  Christopher Nolan
Star Wars: Episode VII - The Force Awakens    NaN        Doug Walker

                                            num_critic_for_reviews  duration  \
movie_title
Avatar                                                       723.0     178.0
Pirates of the Caribbean: At World's End                     302.0     169.0
Spectre                                                      602.0     148.0
The Dark Knight Rises                                        813.0     164.0
Star Wars: Episode VII - The Force Awakens                     NaN       NaN

                                            director_facebook_likes  \
movie_title
Avatar                                                          0.0
Pirates of the Caribbean: At World's End                      563.0
Spectre                                                         0.0
The Dark Knight Rises                                       22000.0
Star Wars: Episode VII - The Force Awakens                    131.0

                                            actor_3_facebook_likes  \
movie_title
Avatar                                                       855.0
Pirates of the Caribbean: At World's End                    1000.0
Spectre                                                      161.0
The Dark Knight Rises                                      23000.0
Star Wars: Episode VII - The Force Awakens                     NaN

                                                actor_2_name  \
movie_title
Avatar                                      Joel David Moore
Pirates of the Caribbean: At World's End       Orlando Bloom
Spectre                                         Rory Kinnear
The Dark Knight Rises                         Christian Bale
Star Wars: Episode VII - The Force Awakens        Rob Walker

                                            actor_1_facebook_likes  \
movie_title
Avatar                                                      1000.0
Pirates of the Caribbean: At World's End                   40000.0
Spectre                                                    11000.0
The Dark Knight Rises                                      27000.0
Star Wars: Episode VII - The Force Awakens                   131.0

                                                  gross  \
movie_title
Avatar                                      760505847.0
Pirates of the Caribbean: At World's End    309404152.0
Spectre                                     200074175.0
The Dark Knight Rises                       448130642.0
Star Wars: Episode VII - The Force Awakens          NaN

                                                                     genres  \
movie_title
Avatar                                      Action|Adventure|Fantasy|Sci-Fi
Pirates of the Caribbean: At World's End           Action|Adventure|Fantasy
Spectre                                           Action|Adventure|Thriller
The Dark Knight Rises                                       Action|Thriller
Star Wars: Episode VII - The Force Awakens                      Documentary

                                            ... num_user_for_reviews  \
movie_title                                 ...
Avatar                                      ...               3054.0
Pirates of the Caribbean: At World's End    ...               1238.0
Spectre                                     ...                994.0
The Dark Knight Rises                       ...               2701.0
Star Wars: Episode VII - The Force Awakens  ...                  NaN

                                            language  country content_rating  \
movie_title
Avatar                                       English      USA          PG-13
Pirates of the Caribbean: At World's End     English      USA          PG-13
Spectre                                      English       UK          PG-13
The Dark Knight Rises                        English      USA          PG-13
Star Wars: Episode VII - The Force Awakens       NaN      NaN            NaN

                                                 budget title_year  \
movie_title
Avatar                                      237000000.0     2009.0
Pirates of the Caribbean: At World's End    300000000.0     2007.0
Spectre                                     245000000.0     2015.0
The Dark Knight Rises                       250000000.0     2012.0
Star Wars: Episode VII - The Force Awakens          NaN        NaN

                                           actor_2_facebook_likes  imdb_score  \
movie_title
Avatar                                                      936.0         7.9
Pirates of the Caribbean: At World's End                   5000.0         7.1
Spectre                                                     393.0         6.8
The Dark Knight Rises                                     23000.0         8.5
Star Wars: Episode VII - The Force Awakens                   12.0         7.1

                                           aspect_ratio movie_facebook_likes
movie_title
Avatar                                             1.78                33000
Pirates of the Caribbean: At World's End           2.35                    0
Spectre                                            2.35                85000
The Dark Knight Rises                              2.35               164000
Star Wars: Episode VII - The Force Awakens          NaN                    0

[5 rows x 27 columns]

Conversely, it is possible to turn the index into a column with the reset_index method. This will make movie_title a column again and revert the index back to a RangeIndex. reset_index always puts the column as the very first one in the DataFrame, so the columns may not be in their original order:

In [40]:
Movie_DF4 = Movie_DF3.reset_index()

Movie_DF4.head()

,movie_title,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

### **Adding or Dropping Columns from a DataFrame**

**Adding new column to a DataFrame**

In [41]:
# Count & Display the number of Columns in a Dataframe

Movie_DF.columns.size

28

In [106]:
# Add a New column to a DataFrame

Movie_DF['Tot_FB_Actors_Likes'] = Movie_DF.actor_1_facebook_likes + Movie_DF.actor_2_facebook_likes + Movie_DF.actor_3_facebook_likes

In [107]:
# Count & Display the number of Columns in a Dataframe after adding a new column

Movie_DF.columns.size

29

In [108]:
# Drop the new column from the Dataframe

Movie_DF.drop('Tot_FB_Actors_Likes',axis='columns' , inplace=True)

In [109]:
# Count & Display the number of Columns in a Dataframe after dropping the new column

Movie_DF.columns.size

28

**DataFrame Operations **

In the earlier section of this script , We had extracted single column from a DataFrame resulting in a SERIES . But , now , lets extract multiple columns from the DataFrame .

In [111]:
# Creata a DataFrame which is consisting of subset of the columns from the Original dataFrame

Movie_actor_director = Movie_DF[['actor_1_name', 'actor_2_name','actor_3_name', 'director_name']]

Movie_actor_director.head()

      actor_1_name      actor_2_name          actor_3_name      director_name
0      CCH Pounder  Joel David Moore             Wes Studi      James Cameron
1      Johnny Depp     Orlando Bloom        Jack Davenport     Gore Verbinski
2  Christoph Waltz      Rory Kinnear      Stephanie Sigman         Sam Mendes
3        Tom Hardy    Christian Bale  Joseph Gordon-Levitt  Christopher Nolan
4      Doug Walker        Rob Walker                   NaN        Doug Walker

In [114]:
Movie_DF['actor_1_name']

0                   CCH Pounder
1                   Johnny Depp
2               Christoph Waltz
3                     Tom Hardy
4                   Doug Walker
5                  Daryl Sabara
6                  J.K. Simmons
7                  Brad Garrett
8               Chris Hemsworth
9                  Alan Rickman
10                 Henry Cavill
11                 Kevin Spacey
12           Giancarlo Giannini
13                  Johnny Depp
14                  Johnny Depp
15                 Henry Cavill
16               Peter Dinklage
17              Chris Hemsworth
18                  Johnny Depp
19                   Will Smith
20                 Aidan Turner
21                   Emma Stone
22                    Mark Addy
23                 Aidan Turner
24              Christopher Lee
25                  Naomi Watts
26            Leonardo DiCaprio
27            Robert Downey Jr.
28                  Liam Neeson
29          Bryce Dallas Howard
                 ...
4886                   Franky G
4887                Matt Frewer
4888             Tommy Pallotta
4889                Tjasa Ferme
4890             Kristen Seavey
4891             Shannen Fields
4892            Ashley Tramonte
4893              Robbie Barnes
4894               Mark Duplass
4895                 Paul Ogola
4896           Zoe Lister-Jones
4897                Sean Whalen
4898                     Divine
4899              Maggie Cheung
4900    Fereshteh Sadre Orafaiy
4901          Patrick O'Donnell
4902               Kôji Yakusho
4903        Tatiana Suarez-Pico
4904              Julianna Pitt
4905               Peter Greene
4906              Shane Carruth
4907                Ian Gamazon
4908            Carlos Gallardo
4909             Richard Jewell
4910                Kerry Bishé
4911                Eric Mabius
4912                Natalie Zea
4913                Eva Boehnke
4914                  Alan Ruck
4915                John August
Name: actor_1_name, Length: 4916, dtype: object

In [113]:
Movie_DF[['actor_1_name']]

                 actor_1_name
0                 CCH Pounder
1                 Johnny Depp
2             Christoph Waltz
3                   Tom Hardy
4                 Doug Walker
5                Daryl Sabara
6                J.K. Simmons
7                Brad Garrett
8             Chris Hemsworth
9                Alan Rickman
10               Henry Cavill
11               Kevin Spacey
12         Giancarlo Giannini
13                Johnny Depp
14                Johnny Depp
15               Henry Cavill
16             Peter Dinklage
17            Chris Hemsworth
18                Johnny Depp
19                 Will Smith
20               Aidan Turner
21                 Emma Stone
22                  Mark Addy
23               Aidan Turner
24            Christopher Lee
25                Naomi Watts
26          Leonardo DiCaprio
27          Robert Downey Jr.
28                Liam Neeson
29        Bryce Dallas Howard
...                       ...
4886                 Franky G
4887              Matt Frewer
4888           Tommy Pallotta
4889              Tjasa Ferme
4890           Kristen Seavey
4891           Shannen Fields
4892          Ashley Tramonte
4893            Robbie Barnes
4894             Mark Duplass
4895               Paul Ogola
4896         Zoe Lister-Jones
4897              Sean Whalen
4898                   Divine
4899            Maggie Cheung
4900  Fereshteh Sadre Orafaiy
4901        Patrick O'Donnell
4902             Kôji Yakusho
4903      Tatiana Suarez-Pico
4904            Julianna Pitt
4905             Peter Greene
4906            Shane Carruth
4907              Ian Gamazon
4908          Carlos Gallardo
4909           Richard Jewell
4910              Kerry Bishé
4911              Eric Mabius
4912              Natalie Zea
4913              Eva Boehnke
4914                Alan Ruck
4915              John August

[4916 rows x 1 columns]

**Use the select_dtypes method to select only the integer columns:**

In [115]:


Movie_DF.get_dtype_counts()

object     12
float64    13
int64       3
dtype: int64

In [116]:
# Extract only those columns which are of Integer Data Type

Movie_DF.select_dtypes(include=['int'])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[4916 rows x 0 columns]

In [117]:
# Extract only those columns which are of Numeric Data Type

Movie_DF.select_dtypes(include=['number']).head()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,723.0,178.0,0.0,855.0,1000.0,760505847.0,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000
1,302.0,169.0,563.0,1000.0,40000.0,309404152.0,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0
2,602.0,148.0,0.0,161.0,11000.0,200074175.0,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000
3,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,NaN,131.0,NaN,131.0,NaN,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0

**Extracting Columns where the column name contains specific string **

Lets extract those columns only which has 'facebook' in the column name

In [119]:
# Extract only those columns which has 'facebook' in the Column name

Movie_DF.filter(like='actor').head()

,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,actor_1_name,actor_3_name,actor_2_facebook_likes
0,855.0,Joel David Moore,1000.0,CCH Pounder,Wes Studi,936.0
1,1000.0,Orlando Bloom,40000.0,Johnny Depp,Jack Davenport,5000.0
2,161.0,Rory Kinnear,11000.0,Christoph Waltz,Stephanie Sigman,393.0
3,23000.0,Christian Bale,27000.0,Tom Hardy,Joseph Gordon-Levitt,23000.0
4,NaN,Rob Walker,131.0,Doug Walker,NaN,12.0

### Methods & Attributes used for DataFrame Objects

**Attributes**

    a) shape : returns the number of rows & columns in a DatFrame
    b) size  : Returns the total numbers of elements in a Dataframe

In [51]:
# get the shape & size of a DataFrame

print(Movie_DF.shape)

print(Movie_DF.size)

(4916, 28)
137648

Methods available with DataFrame object -

    a) count()
    b) describe()

In [120]:
# count method is used to find the number of non-missing values for each column.

print(Movie_DF.count())

color                        4897
director_name                4814
num_critic_for_reviews       4867
duration                     4901
director_facebook_likes      4814
actor_3_facebook_likes       4893
actor_2_name                 4903
actor_1_facebook_likes       4909
gross                        4054
genres                       4916
actor_1_name                 4909
movie_title                  4916
num_voted_users              4916
cast_total_facebook_likes    4916
actor_3_name                 4893
facenumber_in_poster         4903
plot_keywords                4764
movie_imdb_link              4916
num_user_for_reviews         4895
language                     4904
country                      4911
content_rating               4616
budget                       4432
title_year                   4810
actor_2_facebook_likes       4903
imdb_score                   4916
aspect_ratio                 4590
movie_facebook_likes         4916
dtype: int64

In [53]:
# Find the Statistical Summary of each column in the DataFrame

print(Movie_DF.describe())

       num_critic_for_reviews     duration  director_facebook_likes  \
count             4867.000000  4901.000000              4814.000000
mean               137.988905   107.090798               691.014541
std                120.239379    25.286015              2832.954125
min                  1.000000     7.000000                 0.000000
25%                 49.000000    93.000000                 7.000000
50%                108.000000   103.000000                48.000000
75%                191.000000   118.000000               189.750000
max                813.000000   511.000000             23000.000000

       actor_3_facebook_likes  actor_1_facebook_likes         gross  \
count             4893.000000             4909.000000  4.054000e+03
mean               631.276313             6494.488491  4.764451e+07
std               1625.874802            15106.986884  6.737255e+07
min                  0.000000                0.000000  1.620000e+02
25%                132.000000              607.000000  5.019656e+06
50%                366.000000              982.000000  2.504396e+07
75%                633.000000            11000.000000  6.110841e+07
max              23000.000000           640000.000000  7.605058e+08

       num_voted_users  cast_total_facebook_likes  facenumber_in_poster  \
count     4.916000e+03                4916.000000           4903.000000
mean      8.264492e+04                9579.815907              1.377320
std       1.383222e+05               18164.316990              2.023826
min       5.000000e+00                   0.000000              0.000000
25%       8.361750e+03                1394.750000              0.000000
50%       3.313250e+04                3049.000000              1.000000
75%       9.377275e+04               13616.750000              2.000000
max       1.689764e+06              656730.000000             43.000000

       num_user_for_reviews        budget   title_year  \
count           4895.000000  4.432000e+03  4810.000000
mean             267.668846  3.654749e+07  2002.447609
std              372.934839  1.002427e+08    12.453977
min                1.000000  2.180000e+02  1916.000000
25%               64.000000  6.000000e+06  1999.000000
50%              153.000000  1.985000e+07  2005.000000
75%              320.500000  4.300000e+07  2011.000000
max             5060.000000  4.200000e+09  2016.000000

       actor_2_facebook_likes   imdb_score  aspect_ratio  movie_facebook_likes
count             4903.000000  4916.000000   4590.000000           4916.000000
mean              1621.923516     6.437429      2.222349           7348.294142
std               4011.299523     1.127802      1.402940          19206.016458
min                  0.000000     1.600000      1.180000              0.000000
25%                277.000000     5.800000      1.850000              0.000000
50%                593.000000     6.600000      2.350000            159.000000
75%                912.000000     7.200000      2.350000           2000.000000
max             137000.000000     9.500000     16.000000         349000.000000

Lets create a DataFrame by ourself from Scratch

In [121]:
data = {
    'apples': [3, 2, 0, 1], 
    'oranges': [0, 3, 7, 2]
}

print(data)

print(type(data))

{'apples': [3, 2, 0, 1], 'oranges': [0, 3, 7, 2]}
<class 'dict'>

In [122]:
purchases_df = pd.DataFrame(data)

purchases_df

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

#### Lets decipher the above code

Each (key, value) item in data corresponds to a column in the resulting DataFrame.

The Index of this DataFrame was given to us on creation as the numbers 0-3, but we could also create our own when we initialize the DataFrame.

Let's have customer names as our index:

In [124]:
purchases_df2 = pd.DataFrame(data, index=['PRM', 'Robert', 'Lily', 'David'])

purchases_df2

        apples  oranges
PRM          3        0
Robert       2        3
Lily         0        7
David        1        2

### Extracting Data from a DataFrame

Based on the Purchased DataFrame created above , now we could locate a customer's order by using their name:

In [125]:
purchases_df2.loc['PRM']

apples     3
oranges    0
Name: PRM, dtype: int64

#### Append DataFrames

In [126]:
purchases_df3 = purchases_df.append(purchases_df2)

print(purchases_df3.shape)

print(purchases_df3)

(8, 2)
        apples  oranges
0            3        0
1            2        3
2            0        7
3            1        2
PRM          3        0
Robert       2        3
Lily         0        7
David        1        2

### Drop Duplicate Columns

In [127]:
purchases_df3.drop_duplicates()

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [128]:
purchases_df4 = purchases_df3.drop_duplicates()

print(purchases_df4)

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [129]:
print(purchases_df3)

purchases_df3.drop_duplicates(inplace=True)

print(purchases_df3)

        apples  oranges
0            3        0
1            2        3
2            0        7
3            1        2
PRM          3        0
Robert       2        3
Lily         0        7
David        1        2
   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

### DataFrame slicing, selecting, extracting

In [130]:
Apple_col = purchases_df['apples']

type(Apple_col)

pandas.core.series.Series

In [131]:
print(Apple_col)

0    3
1    2
2    0
3    1
Name: apples, dtype: int64

This will return a Series. To extract a column as a DataFrame, you need to pass a list of column names. In our case that's just a single column:

In [132]:
Apple_col2 = purchases_df[['apples']]

type(Apple_col2)

pandas.core.frame.DataFrame

In [70]:
Apple_col2

   apples
0       3
1       2
2       0
3       1

In [133]:
subset = purchases_df[['apples', 'oranges']]

subset.head()

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

By rows

For rows, we have two options:

    .loc - locates by name
    .iloc- locates by numerical index

In [134]:
purchases_df2

        apples  oranges
PRM          3        0
Robert       2        3
Lily         0        7
David        1        2

In [135]:
PRM_Row = purchases_df2.loc["PRM"]

PRM_Row

apples     3
oranges    0
Name: PRM, dtype: int64

In [136]:
Row_1 = purchases_df2.iloc[1]

Row_1

apples     2
oranges    3
Name: Robert, dtype: int64